// ─── LX2 module registry ──────────────────────────────────────────────
// This is the single source of truth for architecture, roadmap, and docs.
// The architecture dashboard and any future tooling imports from here.

export type Phase = 'mvp' | 'soon' | 'later' | 'future'
export type Tier = 'player' | 'organiser' | 'scoring' | 'course' | 'infra' | 'club'
export type Status = 'planned' | 'building' | 'done'

export interface Module {
  id: string
  name: string
  phase: Phase
  tier: Tier
  status: Status
  sub: string
  desc: string
  deps: string[]
  data: string[]
  features: string[]
  tech: string
  prdUrl?: string
  docsUrl?: string
}

export const modules: Record<string, Module> = {
  score_entry: {
    id: 'score_entry',
    name: 'Score entry',
    phase: 'mvp',
    tier: 'player',
    status: 'planned',
    sub: 'Hole-by-hole, offline-first',
    desc: 'Mobile-first hole-by-hole score input. The core interaction during a round. Must work offline with automatic sync when connectivity returns.',
    deps: ['handicap', 'course_db', 'realtime', 'pwa', 'auth'],
    data: ['hole_scores', 'scorecards'],
    features: [
      'One-tap score entry per hole with large targets (48px min)',
      'Running total and Stableford points shown after each hole',
      'Match Play status display ("2 up with 5 to play")',
      'Offline queue — scores saved to IndexedDB, synced on reconnect',
      'Visual sync status indicator (green = synced, amber = pending)',
      'Undo last hole entry',
      'NTP/LD result entry on designated contest holes',
      'Auto-advance to next hole on entry',
    ],
    tech: 'Next.js page with Supabase Realtime subscription. Service worker caches app shell. IndexedDB stores pending scores. Sync manager batches uploads on reconnect.',
  },
  leaderboard: {
    id: 'leaderboard',
    name: 'Live leaderboard',
    phase: 'mvp',
    tier: 'player',
    status: 'planned',
    sub: 'Real-time, TV mode',
    desc: 'Real-time ranking page that auto-updates as scores arrive via WebSocket. Shareable URL. TV/full-screen display mode for clubhouse screens.',
    deps: ['stableford', 'strokeplay', 'matchplay', 'realtime', 'course_db'],
    data: ['scorecards', 'hole_scores', 'events', 'event_players'],
    features: [
      'Auto-updating positions as scores arrive (sub-second latency)',
      'Format-aware: points for Stableford, net strokes for Stroke Play, match status for Match Play',
      '"Through X holes" indicator per player',
      'NTP/LD results shown alongside main leaderboard',
      'TV mode: full-screen, auto-scroll through flights, large typography',
      'Shareable URL with Open Graph preview',
      'Player highlighting — tap to see hole-by-hole breakdown',
      'Countback tiebreaker display',
    ],
    tech: 'Next.js page subscribing to Supabase Realtime on scorecards table. Client-side scoring engine recalculates positions on each change.',
  },
  results: {
    id: 'results',
    name: 'Results & history',
    phase: 'mvp',
    tier: 'player',
    status: 'planned',
    sub: 'Permanent shareable page',
    desc: 'Permanent results page at a stable URL. Final standings, NTP/LD winners, prize info. The thing players share and come back to.',
    deps: ['stableford', 'strokeplay', 'event_create', 'course_db'],
    data: ['events', 'scorecards', 'contest_entries'],
    features: [
      'Final standings with positions, scores/points, handicap used',
      'NTP/LD contest winners with distances',
      'Full scorecard view per player (hole-by-hole breakdown)',
      'Share buttons (WhatsApp, copy link) with rich preview',
      'Persistent URL — never expires',
    ],
    tech: 'Static generation with ISR once event is finalised. Cached at edge for fast loading.',
  },
  event_create: {
    id: 'event_create',
    name: 'Event creation',
    phase: 'mvp',
    tier: 'organiser',
    status: 'planned',
    sub: 'Date, course, format, fee, NTP/LD',
    desc: 'The organiser creates an event by selecting a date, course, format, entry fee, and configuring side contests. Top of the funnel.',
    deps: ['course_db', 'auth', 'payments'],
    data: ['events', 'courses'],
    features: [
      'Select or search from imported UK course database',
      'Choose format: Stableford, Stroke Play, Match Play',
      'Set entry fee (or free event)',
      'Designate NTP/LD holes from the course scorecard',
      'Set max players and group size',
      'Configure handicap allowance',
      'Generate unique shareable invite link',
      'Duplicate event for recurring society fixtures',
    ],
    tech: 'Next.js form page. Writes to events table in Supabase. Course selection uses typeahead search against course_db.',
  },
  invite: {
    id: 'invite',
    name: 'Invite & RSVP',
    phase: 'mvp',
    tier: 'organiser',
    status: 'planned',
    sub: 'Shareable link, no account needed',
    desc: 'Shareable link flow. Players tap the link, see event details, enter their name and handicap, and confirm attendance. No account creation required.',
    deps: ['event_create', 'auth'],
    data: ['event_players', 'users'],
    features: [
      'Shareable URL with rich Open Graph preview for WhatsApp/iMessage',
      'No account required to RSVP — just name, email, and handicap index',
      'Progressive account creation (optional)',
      'RSVP status: confirmed / declined / waitlisted',
      'Organiser can manually add players',
      'Automatic email confirmation with calendar invite',
    ],
    tech: 'Public Next.js page (no auth required). Supabase anonymous auth for RSVP, upgraded to magic link auth on account creation.',
  },
  payments: {
    id: 'payments',
    name: 'Payments',
    phase: 'mvp',
    tier: 'organiser',
    status: 'planned',
    sub: 'Stripe Checkout, live tracker',
    desc: 'Stripe Checkout for entry fee collection. Organiser sees real-time payment status. Players pay when they RSVP.',
    deps: ['invite', 'event_create'],
    data: ['payments', 'event_players'],
    features: [
      'Stripe Checkout embedded in RSVP flow',
      'Real-time payment status on organiser dashboard',
      'Manual "mark as paid" for cash payments',
      'Automatic refund if player withdraws (configurable)',
      'Payment reminder email to unpaid players',
      'Stripe Connect for club payouts (Phase 3)',
    ],
    tech: 'Stripe Checkout Session via Next.js API route. Webhook handler updates payment status in Supabase.',
  },
  dashboard: {
    id: 'dashboard',
    name: 'Organiser dashboard',
    phase: 'mvp',
    tier: 'organiser',
    status: 'planned',
    sub: 'Flights, status, proxy scoring',
    desc: "The organiser's command centre. View confirmed players, payment status, manage groups/flights, enter scores on behalf of players.",
    deps: ['event_create', 'invite', 'payments', 'score_entry'],
    data: ['events', 'event_players', 'payments', 'scorecards'],
    features: [
      'Player list with RSVP and payment status',
      'Drag-and-drop flight/group management',
      'Auto-generate balanced flights from handicaps',
      'Proxy score entry (enter scores for any player)',
      'Print-friendly draw sheet and start sheet',
      'Live event status overview during play',
      'Finalise event and generate results',
      'Export results to CSV',
    ],
    tech: 'Next.js page with Supabase Realtime. Desktop-optimised.',
  },
  stableford: {
    id: 'stableford',
    name: 'Stableford engine',
    phase: 'mvp',
    tier: 'scoring',
    status: 'planned',
    sub: 'Points from net score vs par',
    desc: 'Calculates Stableford points per hole from gross strokes, par, and handicap strokes received. Most common UK society format.',
    deps: ['handicap', 'course_db'],
    data: [],
    features: [
      'Net score = gross strokes minus handicap strokes on hole',
      'Points: 0 (double+), 1 (bogey), 2 (par), 3 (birdie), 4 (eagle), 5 (albatross)',
      'Pick-up handling: 0 points for incomplete holes',
      'Countback tiebreaker: back 9, 6, 3, last hole',
      '95% handicap allowance (configurable)',
    ],
    tech: 'Pure TypeScript in @lx2/scoring. Zero database dependency. packages/scoring/src/stableford.ts',
  },
  strokeplay: {
    id: 'strokeplay',
    name: 'Stroke play engine',
    phase: 'mvp',
    tier: 'scoring',
    status: 'planned',
    sub: 'Gross and net totals',
    desc: 'Total gross strokes minus playing handicap = net score. Lower is better.',
    deps: ['handicap', 'course_db'],
    data: [],
    features: [
      'Gross total = sum of strokes',
      'Net total = gross minus playing handicap',
      'Relative to par display (+3, -1, E)',
      'NR (No Return) for incomplete rounds',
      'Countback tiebreaker on net scores',
    ],
    tech: 'Pure TypeScript in @lx2/scoring. Shares handicap allocation logic with Stableford. packages/scoring/src/strokeplay.ts',
  },
  matchplay: {
    id: 'matchplay',
    name: 'Match play engine',
    phase: 'mvp',
    tier: 'scoring',
    status: 'planned',
    sub: 'Holes up/down, early close',
    desc: 'Each hole is a separate contest. Lower net score wins the hole. Match can end early when result is certain.',
    deps: ['handicap', 'course_db'],
    data: [],
    features: [
      'Hole-by-hole: win / lose / halve on net scores',
      'Handicap based on DIFFERENCE between two players',
      'Match status: "2 up", "all square", "1 down"',
      'Early termination: e.g. "4 and 3"',
      'Dormie detection',
    ],
    tech: 'Pure TypeScript in @lx2/scoring. Different interface — operates on two players simultaneously. packages/scoring/src/matchplay.ts',
  },
  handicap: {
    id: 'handicap',
    name: 'Handicap engine',
    phase: 'mvp',
    tier: 'scoring',
    status: 'planned',
    sub: 'Index → playing HC via slope',
    desc: 'Converts handicap index to playing handicap using WHS formula, then distributes strokes across holes by stroke index. Shared by all scoring engines.',
    deps: ['course_db'],
    data: [],
    features: [
      'Playing HC = round(Index × Slope/113 + (Rating − Par)) × allowance',
      '95% allowance Stableford, 100% stroke, difference-based match',
      'Stroke distribution by stroke index, handles 36+ handicaps',
      'Plus handicap (negative) support',
      'Manual handicap index entry (MVP)',
      'WHS API lookup (Phase 4 — requires ISV licence)',
    ],
    tech: 'Pure TypeScript in @lx2/scoring. packages/scoring/src/handicap.ts',
  },
  course_db: {
    id: 'course_db',
    name: 'Course database',
    phase: 'mvp',
    tier: 'course',
    status: 'planned',
    sub: 'Par, SI, yardage, slope, rating',
    desc: 'All UK golf course data. Seeded from golfcourseapi.com (~30,000 courses, free). Verified manually for active courses.',
    deps: [],
    data: ['courses', 'course_holes', 'course_tees'],
    features: [
      '~30,000 UK courses from golfcourseapi.com (free bulk CSV)',
      'Per hole: par, stroke index',
      'Per tee: name, yardage, slope rating, course rating',
      'Course search with typeahead (name, location)',
      'Admin: manual course entry/edit for missing data',
      'Cumberwell Park five 9-hole loops pre-verified',
    ],
    tech: 'Supabase tables: courses, course_holes, course_tees. Import script in packages/db/scripts/import-courses.ts.',
  },
  auth: {
    id: 'auth',
    name: 'Authentication',
    phase: 'mvp',
    tier: 'infra',
    status: 'planned',
    sub: 'Magic links + anonymous play',
    desc: 'Magic link email auth with anonymous-first flow. Players can score a full round before being prompted to create an account.',
    deps: [],
    data: ['users'],
    features: [
      'Email magic link login (no password)',
      'Anonymous play: score first, account later',
      'Google and Apple OAuth (Phase 2)',
      'Organiser vs player role separation',
      'Row-level security on all Supabase tables',
    ],
    tech: 'Supabase Auth. Magic link flow. Anonymous session with progressive account creation.',
  },
  realtime: {
    id: 'realtime',
    name: 'Realtime layer',
    phase: 'mvp',
    tier: 'infra',
    status: 'planned',
    sub: 'WebSocket subscriptions via Supabase',
    desc: 'Live score updates pushed to all connected leaderboard clients the moment a hole score is saved. Sub-second latency.',
    deps: ['auth'],
    data: ['hole_scores', 'scorecards'],
    features: [
      'Supabase Realtime on hole_scores and scorecards tables',
      'Client-side recalculation on each change event',
      'Presence: show which players are currently scoring',
      'Reconnection handling with state reconciliation',
    ],
    tech: 'Supabase Realtime (postgres_changes). Enabled in 001_initial_schema.sql migration. Client hook in apps/web.',
  },
  pwa: {
    id: 'pwa',
    name: 'PWA / offline mode',
    phase: 'soon',
    tier: 'infra',
    status: 'planned',
    sub: 'Add to home screen, offline scoring',
    desc: 'Service worker caches the app shell and scoring pages. Scores written to IndexedDB offline, synced automatically on reconnect.',
    deps: ['score_entry', 'auth'],
    data: [],
    features: [
      'Service worker for offline scorecard',
      'IndexedDB buffering of scores',
      'Background sync on reconnect',
      '"Add to home screen" prompt',
      'Works on iOS Safari and Android Chrome',
    ],
    tech: 'next-pwa or custom service worker. Workbox. IndexedDB via idb library.',
  },
  profiles: {
    id: 'profiles',
    name: 'Player profiles',
    phase: 'soon',
    tier: 'player',
    status: 'planned',
    sub: 'Stats across events',
    desc: 'Cumulative stats across all events a player has played. Win/loss record, scoring average, handicap trend.',
    deps: ['auth', 'stableford', 'results'],
    data: ['users', 'scorecards', 'events'],
    features: [
      'Win/loss/draw record across events',
      'Average Stableford points, scoring average',
      'Best and worst rounds, most recent',
      'Events played list with links to results',
      'Handicap trend over time',
    ],
    tech: 'Server-rendered page with aggregation queries. Materialised views if query performance degrades.',
  },
  skins: {
    id: 'skins',
    name: 'Skins engine',
    phase: 'soon',
    tier: 'scoring',
    status: 'planned',
    sub: 'Carry-over pot per hole',
    desc: 'Each hole is worth a pot. Carry-over if tied. Runs alongside a main Stableford event.',
    deps: ['stableford', 'handicap'],
    data: [],
    features: [
      'Each hole worth 1 skin (carry-over if tied)',
      'Configurable skin value / entry fee',
      'Carry-over accumulation and resolution',
      'Works alongside Stableford main event',
    ],
    tech: 'Extension of @lx2/scoring. Operates on completed hole_scores for all players.',
  },
  rvb: {
    id: 'rvb',
    name: 'Reds vs Blues',
    phase: 'soon',
    tier: 'scoring',
    status: 'planned',
    sub: 'Ryder Cup team format',
    desc: 'Ryder Cup-style team match. Two teams, multiple match play pairings. Aggregate team score.',
    deps: ['matchplay', 'handicap'],
    data: ['events', 'event_players'],
    features: [
      'Two teams with configurable names and colours',
      'Multiple concurrent match play pairings',
      'Aggregate team score',
      'Up to 72 players (36 per team)',
      'Projected team result from current match states',
    ],
    tech: 'Extends Match Play engine. Additional UI for team composition and aggregate scoring.',
  },
  club_profile: {
    id: 'club_profile',
    name: 'Club profile',
    phase: 'later',
    tier: 'club',
    status: 'planned',
    sub: 'Club-managed page and events',
    desc: 'Clubs can claim their profile, manage their events centrally, and view member engagement stats.',
    deps: ['event_create', 'auth', 'course_db'],
    data: ['clubs', 'events'],
    features: [
      'Claim and verify club profile',
      'Club-managed event calendar',
      'Member roster management',
      'Engagement analytics',
      'Custom branding (logo, colours)',
    ],
    tech: 'Extended auth roles. clubs table + club_members junction. Supabase RLS policies for club admins.',
  },
  whs: {
    id: 'whs',
    name: 'WHS integration',
    phase: 'later',
    tier: 'course',
    status: 'planned',
    sub: 'Live handicap lookup',
    desc: 'Live WHS handicap lookup via England Golf / DotGolf API. Requires ISV licence.',
    deps: ['handicap', 'auth'],
    data: ['users'],
    features: [
      'Handicap index lookup by CDH number',
      'Auto-populate on player record',
      'Submit qualifying round results',
      'Requires ISV licence from England Golf',
    ],
    tech: 'DotGolf API. ISV licence required. Manual entry remains as fallback throughout.',
  },
  club_erp: {
    id: 'club_erp',
    name: 'Club ERP layer',
    phase: 'later',
    tier: 'club',
    status: 'planned',
    sub: 'Cumberwell-first integration',
    desc: 'Full club management: member records, competition calendar, tee time booking. Pilot target: Cumberwell Park.',
    deps: ['club_profile', 'auth', 'payments'],
    data: ['clubs', 'events', 'users'],
    features: [
      'Member management (import from intelligentgolf)',
      'Competition calendar and results',
      'Tee time booking (replaces golfbook/255it)',
      'Club admin dashboard',
      'Reporting for club committees',
    ],
    tech: 'Extended Supabase schema. Integration with intelligentgolf export format.',
  },
  discovery: {
    id: 'discovery',
    name: 'Event discovery',
    phase: 'future',
    tier: 'club',
    status: 'planned',
    sub: 'Find and join public events',
    desc: 'Public marketplace for finding and joining open golf events. The network-effects play. Requires critical mass.',
    deps: ['event_create', 'invite', 'payments', 'club_profile'],
    data: ['events'],
    features: [
      'Browse public events by location, date, format',
      'Search and filter',
      'Book and pay directly',
      'Club-promoted events',
    ],
    tech: 'Next.js with geolocation-based search. Supabase PostGIS extension for location queries.',
  },
  native_app: {
    id: 'native_app',
    name: 'Native mobile app',
    phase: 'future',
    tier: 'infra',
    status: 'planned',
    sub: 'React Native (iOS + Android)',
    desc: 'Native iOS and Android app sharing scoring engines and business logic. Triggered at 500+ regular web users.',
    deps: ['score_entry', 'auth'],
    data: [],
    features: [
      'React Native sharing @lx2/scoring package',
      'App Store + Google Play distribution',
      'GPS yardage',
      'Push notifications for leaderboard updates',
    ],
    tech: 'React Native + Expo. Shared TypeScript from @lx2/scoring. Supabase JS SDK.',
  },
}

export const tierOrder: Tier[] = ['player', 'organiser', 'scoring', 'course', 'infra', 'club']

export const tierLabels: Record<Tier, string> = {
  player: 'Player-facing experience',
  organiser: 'Organiser tools',
  scoring: 'Scoring engines',
  course: 'Course & handicap data',
  infra: 'Platform infrastructure',
  club: 'Club-facing (phase 3–4)',
}

export const tierNotes: Partial<Record<Tier, string>> = {
  scoring: 'Pure functions in @lx2/scoring — zero database dependency',
  infra: 'Shared by all tiers above',
}

export const phaseLabels: Record<Phase, string> = {
  mvp: 'MVP',
  soon: 'Phase 2',
  later: 'Phase 3',
  future: 'Phase 4',
}
