// ── Golf-playing countries sorted alphabetically ─────────────────────────────
// Used by scorecard upload (dropdown + continent auto-fill).

export interface CountryEntry {
  name: string
  continent: string
}

export const GOLF_COUNTRIES: CountryEntry[] = [
  { name: 'Argentina', continent: 'South America' },
  { name: 'Australia', continent: 'Oceania' },
  { name: 'Austria', continent: 'Europe' },
  { name: 'Bahamas', continent: 'North America' },
  { name: 'Bahrain', continent: 'Asia' },
  { name: 'Barbados', continent: 'North America' },
  { name: 'Belgium', continent: 'Europe' },
  { name: 'Bermuda', continent: 'North America' },
  { name: 'Botswana', continent: 'Africa' },
  { name: 'Brazil', continent: 'South America' },
  { name: 'Bulgaria', continent: 'Europe' },
  { name: 'Cambodia', continent: 'Asia' },
  { name: 'Canada', continent: 'North America' },
  { name: 'Chile', continent: 'South America' },
  { name: 'China', continent: 'Asia' },
  { name: 'Colombia', continent: 'South America' },
  { name: 'Costa Rica', continent: 'North America' },
  { name: 'Croatia', continent: 'Europe' },
  { name: 'Cyprus', continent: 'Europe' },
  { name: 'Czech Republic', continent: 'Europe' },
  { name: 'Denmark', continent: 'Europe' },
  { name: 'Dominican Republic', continent: 'North America' },
  { name: 'Ecuador', continent: 'South America' },
  { name: 'Egypt', continent: 'Africa' },
  { name: 'England', continent: 'Europe' },
  { name: 'Estonia', continent: 'Europe' },
  { name: 'Fiji', continent: 'Oceania' },
  { name: 'Finland', continent: 'Europe' },
  { name: 'France', continent: 'Europe' },
  { name: 'Germany', continent: 'Europe' },
  { name: 'Ghana', continent: 'Africa' },
  { name: 'Greece', continent: 'Europe' },
  { name: 'Hungary', continent: 'Europe' },
  { name: 'Iceland', continent: 'Europe' },
  { name: 'India', continent: 'Asia' },
  { name: 'Indonesia', continent: 'Asia' },
  { name: 'Ireland', continent: 'Europe' },
  { name: 'Italy', continent: 'Europe' },
  { name: 'Jamaica', continent: 'North America' },
  { name: 'Japan', continent: 'Asia' },
  { name: 'Kenya', continent: 'Africa' },
  { name: 'Latvia', continent: 'Europe' },
  { name: 'Lithuania', continent: 'Europe' },
  { name: 'Luxembourg', continent: 'Europe' },
  { name: 'Malaysia', continent: 'Asia' },
  { name: 'Malta', continent: 'Europe' },
  { name: 'Mauritius', continent: 'Africa' },
  { name: 'Mexico', continent: 'North America' },
  { name: 'Montenegro', continent: 'Europe' },
  { name: 'Morocco', continent: 'Africa' },
  { name: 'Myanmar', continent: 'Asia' },
  { name: 'Namibia', continent: 'Africa' },
  { name: 'Nepal', continent: 'Asia' },
  { name: 'Netherlands', continent: 'Europe' },
  { name: 'New Zealand', continent: 'Oceania' },
  { name: 'Nigeria', continent: 'Africa' },
  { name: 'Northern Ireland', continent: 'Europe' },
  { name: 'Norway', continent: 'Europe' },
  { name: 'Oman', continent: 'Asia' },
  { name: 'Pakistan', continent: 'Asia' },
  { name: 'Panama', continent: 'North America' },
  { name: 'Peru', continent: 'South America' },
  { name: 'Philippines', continent: 'Asia' },
  { name: 'Poland', continent: 'Europe' },
  { name: 'Portugal', continent: 'Europe' },
  { name: 'Puerto Rico', continent: 'North America' },
  { name: 'Qatar', continent: 'Asia' },
  { name: 'Romania', continent: 'Europe' },
  { name: 'Saudi Arabia', continent: 'Asia' },
  { name: 'Scotland', continent: 'Europe' },
  { name: 'Serbia', continent: 'Europe' },
  { name: 'Singapore', continent: 'Asia' },
  { name: 'Slovakia', continent: 'Europe' },
  { name: 'Slovenia', continent: 'Europe' },
  { name: 'South Africa', continent: 'Africa' },
  { name: 'South Korea', continent: 'Asia' },
  { name: 'Spain', continent: 'Europe' },
  { name: 'Sri Lanka', continent: 'Asia' },
  { name: 'Sweden', continent: 'Europe' },
  { name: 'Switzerland', continent: 'Europe' },
  { name: 'Taiwan', continent: 'Asia' },
  { name: 'Tanzania', continent: 'Africa' },
  { name: 'Thailand', continent: 'Asia' },
  { name: 'Trinidad and Tobago', continent: 'North America' },
  { name: 'Tunisia', continent: 'Africa' },
  { name: 'Turkey', continent: 'Europe' },
  { name: 'UAE', continent: 'Asia' },
  { name: 'Uganda', continent: 'Africa' },
  { name: 'Uruguay', continent: 'South America' },
  { name: 'USA', continent: 'North America' },
  { name: 'Vietnam', continent: 'Asia' },
  { name: 'Wales', continent: 'Europe' },
  { name: 'Zambia', continent: 'Africa' },
  { name: 'Zimbabwe', continent: 'Africa' },
]

/** Flat list of country names (for dropdowns) */
export const COUNTRY_NAMES = GOLF_COUNTRIES.map(c => c.name)

/** Look up continent by country name */
export function continentForCountry(country: string): string {
  return GOLF_COUNTRIES.find(c => c.name === country)?.continent ?? 'Unknown'
}
